# Generated by Django 5.0.3 on 2024-04-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name']},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
